name: connectbeat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  kakao_flutter_sdk: ^1.9.7+3
  google_sign_in: ^6.2.1
  logging: ^1.2.0
  image_picker: ^0.8.7+5
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  stomp_dart_client: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
